version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: texnoera-postgres-db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "8889:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: texnoera-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8070:80"
    depends_on:
      - postgres
