spring:
  application:
    name: user-service

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:8889/bankdb

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create


mock:
  service:
    json-placeholder:
      url: https://jsonplaceholder.typicode.com/posts