spring:
  application:
    name: user-service

  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:8889/bankdb

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create